name: Bale Downloader Pro

on:
  repository_dispatch:
    types: [download]

jobs:
  download-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade yt-dlp
          mkdir -p downloads

      - name: Process Download
        run: |
          URL="${{ github.event.client_payload.url }}"
          CHAT="${{ github.event.client_payload.chat_id }}"

          echo "URL: $URL"
          echo "CHAT: $CHAT"

          if [ -z "$URL" ]; then
            echo "ERROR: URL is empty"
            exit 1
          fi

          if [[ "$URL" == *"youtube.com"* ]] || [[ "$URL" == *"youtu.be"* ]]; then
            yt-dlp -o "downloads/file.mp4" "$URL"
          else
            wget -O downloads/file "$URL"
          fi

      - name: Send to Bale
        run: |
          FILE=$(ls downloads | head -n 1)

          curl -X POST "https://tapi.bale.ai/bot${{ secrets.BALE_TOKEN }}/sendDocument" \
          -F chat_id="${{ github.event.client_payload.chat_id }}" \
          -F document=@downloads/$FILE
